# NumPy


In [2]:
import numpy as np

## Arreglos

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print(b[1,1])

5


In [9]:
b[1, 1] = 0
b

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [13]:
c = np.array([0, 10, 20, 30, 40, 50])
d = c[1:4]
d

array([10, 20, 30])

In [14]:
d[1] = 100
d

array([ 10, 100,  30])

In [15]:
c

array([  0,  10, 100,  30,  40,  50])

In [17]:
c[3] = -1
c

array([  0,  10, 100,  -1,  40,  50])

In [18]:
d

array([ 10, 100,  -1])

In [19]:
c = np.array([0, 10, 20, 30, 40, 50])
e = c[1:4].copy()
e

array([10, 20, 30])

In [20]:
e[1] = 100
e

array([ 10, 100,  30])

In [21]:
c

array([ 0, 10, 20, 30, 40, 50])

In [31]:
# list(range(-10, 10, 2.5))

In [30]:
np.arange(-10, 10, 2.5)

array([-10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5])

In [32]:
arr = np.arange(0, 11, 1)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [33]:
print(arr[4])   # 4
print(arr[3:6]) # [3, 4, 5]

4
[3 4 5]


In [37]:
# establecer  una condición
print(arr[arr > 7]) # [8, 9, 10]

print(arr[arr % 7 == 0])
# establecer  dos condiciones
print(arr[(arr % 2 == 0) & (arr % 3 == 0)])

[ 8  9 10]
[0 7]
[0 6]


In [41]:
f = np.array([
    [
    [-1, -2, -3],
    [-4, -5, -6],
    [-7, -8, -9]
    ],
    [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ],
])

print(f)        # imprime la matriz completa
print(f[0, 1, 1])

[[[-1 -2 -3]
  [-4 -5 -6]
  [-7 -8 -9]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]
-5


# Funciones básicas

In [43]:
np.zeros((3, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [48]:
np.empty((4, 4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.60219035e-306],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
        1.33512173e-306]])

In [49]:
t = np.linspace(0, 23, num=6)   # inicio, fin, cantidad
print(t)

[ 0.   4.6  9.2 13.8 18.4 23. ]


In [50]:
arr = np.array([2, 5, 0, 9, 2, 4])
arr.sort()
print(arr)  # [0 2 2 4 5 9]

[0 2 2 4 5 9]


In [51]:
arr = np.array([
    [2, 5, 0, 9, 2, 4],
    [3, 0, 0, 7, 2, 5]
])

print(np.sort(arr))
#   [[0 2 2 4 5 9]
#    [0 0 2 3 5 7]]

print(np.sort(arr, axis=0))
#   [[2 0 0 7 2 4]
#    [3 5 0 9 2 5]]

[[0 2 2 4 5 9]
 [0 0 2 3 5 7]]
[[2 0 0 7 2 4]
 [3 5 0 9 2 5]]


# Atributos de los arreglos

In [52]:
a = np.array([1, 2, 3])
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
c = np.array([
    [
    [-1, -2, -3],
    [-4, -5, -6],
    [-7, -8, -9]
    ],
    [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ],
])

In [55]:
c.ndim

3

In [56]:
c.shape

(2, 3, 3)

In [57]:
c.size

18

In [61]:
p = np.empty((2, 2))
p.nbytes

32

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr1.shape)

(8,)


In [63]:
arr2 = arr1.reshape(4, 2)
# print(arr2.shape)   # (4, 2)
arr2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [64]:
arr2 = arr1.reshape(2, 2, 2)
print(arr2.shape)   # (4, 2)
arr2

(2, 2, 2)


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [65]:
x = np.arange(0, 2 * np.pi, 0.01)
y = np.sin(x)

In [66]:
x

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09,
       1.1 , 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 ,
       1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31,
       1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42,
       1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.

In [67]:
np.sin(x)

array([ 0.        ,  0.00999983,  0.01999867,  0.0299955 ,  0.03998933,
        0.04997917,  0.05996401,  0.06994285,  0.07991469,  0.08987855,
        0.09983342,  0.1097783 ,  0.11971221,  0.12963414,  0.13954311,
        0.14943813,  0.15931821,  0.16918235,  0.17902957,  0.18885889,
        0.19866933,  0.2084599 ,  0.21822962,  0.22797752,  0.23770263,
        0.24740396,  0.25708055,  0.26673144,  0.27635565,  0.28595223,
        0.29552021,  0.30505864,  0.31456656,  0.32404303,  0.33348709,
        0.34289781,  0.35227423,  0.36161543,  0.37092047,  0.38018842,
        0.38941834,  0.39860933,  0.40776045,  0.4168708 ,  0.42593947,
        0.43496553,  0.44394811,  0.45288629,  0.46177918,  0.47062589,
        0.47942554,  0.48817725,  0.49688014,  0.50553334,  0.51413599,
        0.52268723,  0.5311862 ,  0.53963205,  0.54802394,  0.55636102,
        0.56464247,  0.57286746,  0.58103516,  0.58914476,  0.59719544,
        0.60518641,  0.61311685,  0.62098599,  0.62879302,  0.63

In [75]:
np.random.rand(3, 3)

array([[0.53769703, 0.50112999, 0.13084179],
       [0.30455599, 0.8557369 , 0.04694179],
       [0.37708203, 0.61668483, 0.90107594]])

In [84]:
np.random.randint(0, 101, size=(2,2, 2))

array([[[97, 70],
        [39, 60]],

       [[ 3, 52],
        [41, 50]]], dtype=int32)

In [92]:
arr = np.array([1, 2, 3, 4, 5])

np.random.shuffle(arr)
arr

array([1, 5, 4, 2, 3])

In [97]:
print(np.random.choice(arr)) 

2


In [98]:
np.random.normal(0, 1, 10)

array([ 0.73567101, -2.02072592,  1.43940529, -0.61696139, -0.03503031,
        0.54488057, -0.64643725, -1.83515728, -0.12605027, -1.66176766])