# NumPy


In [2]:
import numpy as np

## Arreglos

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print(b[1,1])

5


In [9]:
b[1, 1] = 0
b

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [13]:
c = np.array([0, 10, 20, 30, 40, 50])
d = c[1:4]
d

array([10, 20, 30])

In [14]:
d[1] = 100
d

array([ 10, 100,  30])

In [15]:
c

array([  0,  10, 100,  30,  40,  50])

In [17]:
c[3] = -1
c

array([  0,  10, 100,  -1,  40,  50])

In [18]:
d

array([ 10, 100,  -1])

In [19]:
c = np.array([0, 10, 20, 30, 40, 50])
e = c[1:4].copy()
e

array([10, 20, 30])

In [20]:
e[1] = 100
e

array([ 10, 100,  30])

In [21]:
c

array([ 0, 10, 20, 30, 40, 50])

In [31]:
# list(range(-10, 10, 2.5))

In [30]:
np.arange(-10, 10, 2.5)

array([-10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5])

In [32]:
arr = np.arange(0, 11, 1)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [33]:
print(arr[4])   # 4
print(arr[3:6]) # [3, 4, 5]

4
[3 4 5]


In [37]:
# establecer  una condición
print(arr[arr > 7]) # [8, 9, 10]

print(arr[arr % 7 == 0])
# establecer  dos condiciones
print(arr[(arr % 2 == 0) & (arr % 3 == 0)])

[ 8  9 10]
[0 7]
[0 6]


In [41]:
f = np.array([
    [
    [-1, -2, -3],
    [-4, -5, -6],
    [-7, -8, -9]
    ],
    [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ],
])

print(f)        # imprime la matriz completa
print(f[0, 1, 1])

[[[-1 -2 -3]
  [-4 -5 -6]
  [-7 -8 -9]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]
-5
